// Runs pending SQLite migrations against ML_DATABASE_URL (default ./data/ml.sqlite3).
// Postgres migrations are applied with any standard tool (e.g. `psql -f`) against the
// SQL files generated by `npm run db:generate:pg` — see README.
import fs from "node:fs";
import path from "node:path";
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";

const url = process.env.ML_DATABASE_URL ?? "./data/ml.sqlite3";
const filePath = url.startsWith("file:") ? url.slice("file:".length) : url;
const resolved = path.resolve(process.cwd(), filePath);
fs.mkdirSync(path.dirname(resolved), { recursive: true });

const sqlite = new Database(resolved);
sqlite.pragma("journal_mode = WAL");
const db = drizzle(sqlite);

migrate(db, { migrationsFolder: path.resolve(process.cwd(), "src/lib/ml/db/migrations") });

console.log(`ML Foundations Lab: migrations applied to ${resolved}`);
sqlite.close();
